language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.10"

script:
  - npm test;
  - nv=$(./node_modules/.bin/check-node-version --node '>= 6');
    if [[ $nv != *"Error: Wanted node version"* ]] ; then
        npm run lint-types
    fi