language: node_js
node_js:
    - "6"
    - "4"
    - "0.12"
    - "0.10"

script:
    - npm test;
    - nv=$(./node_modules/.bin/check-node-version --node '>= 8') || true;
    - if [[ "$nv" != *"Error"* ]]; then npm run lint-types; fi